"""empty message

Revision ID: 9fafb8b6a0fb
Revises: 
Create Date: 2023-12-14 01:43:25.549884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fafb8b6a0fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(), nullable=True),
    sa.Column('news_image', sa.String(), nullable=True),
    sa.Column('news_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('donation_amount', sa.Integer(), nullable=True),
    sa.Column('stories', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('paypal_email', sa.String(), nullable=True),
    sa.Column('paypal_no', sa.String(), nullable=True),
    sa.Column('bank_no', sa.String(), nullable=True),
    sa.Column('acc_name', sa.String(), nullable=True),
    sa.Column('mpesa_paybill', sa.String(), nullable=True),
    sa.Column('mpesa_acc', sa.String(), nullable=True),
    sa.Column('skrill_country', sa.String(), nullable=True),
    sa.Column('skrill_name', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(length=255), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('stories', sa.String(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    op.drop_table('beneficiaries')
    op.drop_table('admins')
    op.drop_table('charities')
    op.drop_table('users')
    op.drop_table('news')
    # ### end Alembic commands ###
